[project]
name = "bablify"
version = "0.1.0"
description = "Multilingual AI Avatar Chat System optimized for Mac M3 Max - A fork of OpenAvatarChat with WebRTC fixes"
readme = "README.md"
requires-python = ">=3.11.7, <3.12"
dependencies = [
    "aiohttp~=3.11.12",
    "aiortc~=1.12.0",
    "dynaconf~=3.2.7",
    "fastapi[standard]~=0.115.12",
    "fastrtc",
    "gradio~=5.9.1",
    "librosa~=0.10.2",
    "loguru~=0.7.3",
    "modelscope>=1.25.0",
    "numpy<=1.26.4",
    "openai>=1.72.0",
    "opencv-python-headless~=4.11.0",
    "pip>=23.0.0",
    "pyaml>=25.1.0",
    "pydantic~=2.10.6",
    "pyyaml~=6.0.2",
    "scipy~=1.15.1",
    "setuptools>=65.0.0",
    "soundfile~=0.13.1",
    "starlette~=0.41.3",
    "tqdm~=4.67.1",
    "typing-extensions~=4.12.2",
    "uvicorn~=0.34.0",
    "torch==2.4.1",
    "torchvision==0.19.1",
    "torchaudio==2.4.1",
    "python-dotenv>=1.1.0",
    # Mac M3 specific optimizations
    "accelerate>=0.20.0",
    "transformers>=4.30.0",
]

[tool.uv.workspace]
members = [
    "src/handlers/tts/edgetts",
    "src/handlers/tts/cosyvoice",
    "src/handlers/llm/minicpm",
    "src/handlers/avatar/liteavatar",
    "src/handlers/avatar/lam",
    "src/handlers/vad/silerovad",
    "src/handlers/tts/bailian_tts",
    "src/handlers/asr/sensevoice",
    "src/handlers/avatar/musetalk",
]

[tool.uv.sources]
fastrtc = { path = "src/third_party/gradio_webrtc_videochat/dist/fastrtc-0.0.28.dev0-py3-none-any.whl" }

[tool.uv]
no-build-isolation-package = ["chumpy"]
