default:
  logger:
    log_level: "INFO"
  service:
    host: "0.0.0.0"
    port: 8282
    cert_file: "ssl_certs/localhost.crt"
    cert_key: "ssl_certs/localhost.key"
  chat_engine:
    model_root: "models"
    concurrent_limit: 1
    handler_search_path:
      - "src/handlers"
    handler_configs:
      RtcClient:
        module: client/rtc_client/client_handler_rtc
      SileroVad:
        module: vad/silerovad/vad_handler_silero
        speaking_threshold: 0.5
        start_delay: 2048
        end_delay: 5000
        buffer_look_back: 5000
        speech_padding: 512
        use_cpu: true
        num_threads: 4
      Edge_TTS:
        enabled: True
        module: tts/edgetts/tts_handler_edgetts
        voice: "en-US-JennyNeural"
      LLMOpenAICompatible:
        enabled: True
        module: llm/openai_compatible/llm_handler_openai_compatible
        model_name: "gpt-3.5-turbo"
        enable_video_input: False
        history_length: 20
        system_prompt: "You are an AI assistant optimized for Mac M3. You provide helpful, accurate responses in a conversational manner. Keep responses concand engaging."
        api_url: "https://api.openai.com/v1"
        api_key: "" # Set your OpenAI API key here or via environment variable OPENAI_API_KEY
      LiteAvatar:
        enabled: False
        module: avatar/liteavatar/avatar_handler_liteavatar
        avatar_name: 20250408/sample_data
        fps: 20
        debug: false
        enable_fast_mode: true
        use_gpu: false
        num_workers: 4
        memory_efficient: true
        low_memory_mode: true
        batch_inference: false
