default:
  logger:
    log_level: "DEBUG"
  service:
    host: "0.0.0.0"
    port: 8282
    # No SSL certificates - HTTP only for debugging
  chat_engine:
    model_root: "models"
    concurrent_limit: 1
    handler_search_path:
      - "src/handlers"
    handler_configs:
      RtcClient:
        module: client/rtc_client/client_handler_rtc
        # WebRTC settings for localhost
        enable_ice: true
        use_turn: false
        ice_servers:
          - urls: "stun:stun.l.google.com:19302"
        connection_ttl: 900
        debug: true
      SileroVad:
        module: vad/silerovad/vad_handler_silero
        speaking_threshold: 0.5
        start_delay: 2048
        end_delay: 5000
        buffer_look_back: 5000
        speech_padding: 512
        use_cpu: true
        num_threads: 4
        debug: true
      Edge_TTS:
        enabled: True
        module: tts/edgetts/tts_handler_edgetts
        voice: "en-US-JennyNeural"
        sample_rate: 24000
        timeout: 30
        # Mac M3 optimizations
        use_cpu: true
        num_threads: 2
      LLMOpenAICompatible:
        enabled: True
        module: llm/openai_compatible/llm_handler_openai_compatible
        model_name: "qwen2.5vl"
        enable_video_input: True
        history_length: 10
        system_prompt: "You are a helpful AI assistant. Keep responses concise and clear."
        api_url: "http://ollama:11434/v1"
        api_key: "ollama"
        # Timeout and performance settings
        timeout: 45
        max_retries: 2
        temperature: 0.7
        max_tokens: 2000
        stream: false
        # Debug settings
        debug: true
        # Mac M3 specific optimizations
        request_timeout: 60
        connection_timeout: 10
      LiteAvatar:
        enabled: False
        module: avatar/liteavatar/avatar_handler_liteavatar
