default:
  logger:
    log_level: "INFO"
  service:
    host: "0.0.0.0"
    port: 8282
    cert_file: "ssl_certs/localhost.crt"
    cert_key: "ssl_certs/localhost.key"
  chat_engine:
    model_root: "models"
    concurrent_limit: 1
    handler_search_path:
      - "src/handlers"
    # Minimal WebRTC configuration for localhost
    turn_config:
      turn_server:
        urls: ["stun:stun.l.google.com:19302"]
        username: ""
        credential: ""
    handler_configs:
      RtcClient:
        module: client/rtc_client/client_handler_rtc
        connection_ttl: 300
      SileroVad:
        module: vad/silerovad/vad_handler_silero
        speaking_threshold: 0.5
        start_delay: 2048
        end_delay: 5000
        buffer_look_back: 5000
        speech_padding: 512
        use_cpu: true
        num_threads: 4
      Edge_TTS:
        enabled: True
        module: tts/edgetts/tts_handler_edgetts
        voice: "en-US-JennyNeural"
        sample_rate: 24000
      LLMOpenAICompatible:
        enabled: True
        module: llm/openai_compatible/llm_handler_openai_compatible
        model_name: "qwen2.5vl"
        enable_video_input: True
        history_length: 20
        system_prompt: "You are an AI assistant. Keep responses clear and concise."
        api_url: "http://ollama:11434/v1"
        api_key: "ollama"
        timeout: 30
        max_retries: 2
        temperature: 0.7
        max_tokens: 1000
        stream: false
      LiteAvatar:
        enabled: False
        module: avatar/liteavatar/avatar_handler_liteavatar
