default:
  logger:
    log_level: "DEBUG"
  service:
    host: "0.0.0.0"
    port: 8282
    # Remove SSL for debugging
    # cert_file: "ssl_certs/localhost.crt"
    # cert_key: "ssl_certs/localhost.key"
  chat_engine:
    model_root: "models"
    concurrent_limit: 1
    handler_search_path:
      - "src/handlers"
    handler_configs:
      RtcClient:
        module: client/rtc_client/client_handler_rtc
        # Add debug settings
        debug: true
        enable_ice: false
        use_turn: false
      SileroVad:
        module: vad/silerovad/vad_handler_silero
        speaking_threshold: 0.5
        start_delay: 2048
        end_delay: 5000
        buffer_look_back: 5000
        speech_padding: 512
        use_cpu: true
        num_threads: 4
        # Add debug logging
        debug: true
      Edge_TTS:
        enabled: True
        module: tts/edgetts/tts_handler_edgetts
        voice: "en-US-JennyNeural"
        sample_rate: 24000
        # Add timeout settings
        timeout: 30
      LLMOpenAICompatible:
        enabled: True
        module: llm/openai_compatible/llm_handler_openai_compatible
        model_name: "qwen2.5vl"
        enable_video_input: True
        history_length: 20
        system_prompt: "You are an AI assistant. Provide helpful, concise responses."
        api_url: "http://ollama:11434/v1"
        api_key: "ollama"
        # Add timeout and retry settings
        timeout: 60
        max_retries: 3
        temperature: 0.7
        max_tokens: 1000
        # Debug settings
        debug: true
        stream: false
      # Disable avatar for debugging
      LiteAvatar:
        enabled: False
        module: avatar/liteavatar/avatar_handler_liteavatar
