default:
  logger:
    log_level: "INFO"
  service:
    host: "0.0.0.0"
    port: 8282
    cert_file: "ssl_certs/localhost.crt"
    cert_key: "ssl_certs/localhost.key"
  chat_engine:
    model_root: "models"
    handler_search_path:
      - "src/handlers"
    handler_configs:
      RtcClient:
        enabled: True
        module: client/rtc_client/client_handler_rtc
        concurrent_limit: 1
        connection_ttl: 900
        text_only: true
        datachannel_only: true
        enable_audio: false
        enable_video: false
        turn_config:
      SileroVad:
        enabled: False
        module: vad/silerovad/vad_handler_silero
      SenseVoice:
        enabled: False
        module: asr/sensevoice/asr_handler_sensevoice
      EdgeTTS:
        enabled: False
        module: tts/edgetts/tts_handler_edgetts
      LLMOpenAICompatible:
        enabled: False
        module: llm/openai_compatible/llm_handler_openai_compatible
      LiteAvatar:
        enabled: False
        module: avatar/liteavatar/avatar_handler_liteavatar
